import { ChatPromptTemplate } from "@langchain/core/prompts";
import * as z from "zod";

export const QueryAugmentationSchema = z.object({
  queries: z
    .array(z.string())
    .length(3)
    .describe(
      "Exactly 3 English retrieval queries: rephrase or expand from different angles; preserve order IDs, brands, and literals; do not invent facts",
    ),
});

const AUGMENT_PROMPT = ChatPromptTemplate.fromMessages([
    [
      "system",
      `The user provides one question in English. Write exactly 3 retrieval queries (same intent, different angles) for search engines or vector stores:
        Rephrase, change angle, or add light qualifiers; keep proper nouns, model numbers, and order IDs verbatim.
        Output only the structured field queries (array of 3 strings).`,
    ],
    ["human", "{query}"],
]);

function normalizeThreeQueries(original, list) {
    const out = (list ?? [])
        .map((s) => (typeof s === "string" ? s.trim() : ""))
        .filter(Boolean);
        while (out.length < 3) out.push(original);
        return out.slice(0, 3);
}

export async function augmentQuery(chatModel, query) {
    const structured = chatModel.withStructuredOutput(QueryAugmentationSchema);
    const chain = AUGMENT_PROMPT.pipe(structured);
    try {
      const raw = await chain.invoke({ query });
      return { queries: normalizeThreeQueries(query, raw.queries) };
    } catch {
      return { queries: normalizeThreeQueries(query, []) };
    }
}

/** original question before, 
 * followed by the questions generated by LLM; 
 * no duplication, fixed order; each runs ES and Milvus once
*/
export function retrievalQueryStrings(original, augmentation) {
    return [original, ...(augmentation?.queries ?? [])]
        .map((s) => (typeof s === "string" ? s.trim() : ""))
        .filter(Boolean);
}

